# Generated by Django 5.1.3 on 2024-11-29 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_member_phone_member_date_joined_and_more'),
    ]

    #operations = [
    # migrations.AlterField(
            #  model_name='member',
            # name='date_joined',
            # field=models.DateTimeField(default=datetime.datetime.now),
        #  ),
    # ]
