# Generated by Django 5.1.3 on 2024-12-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_member_date_joined'),
    ]

    operations = [
        #migrations.RemoveField(
        # model_name='member',
    # name='date_joined',
        # ),
    ]
