# Generated by Django 5.1.3 on 2024-12-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_member_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
