# Generated by Django 5.1.3 on 2024-12-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
